name: CI

on:
  push:
    branches: ["feature/actuator-safe-apply", "main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov ruff black mypy pyyaml transformers torch --extra-index-url https://download.pytorch.org/whl/cpu
      - name: Build CodeGraph (no-cache)
        run: |
          python -m tools.code_graph ./repo --no-cache --dump || true
      - name: Run verify script
        run: bash scripts/ci_verify.sh
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs

